name: Laravel CI

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4  # Choose the PHP version you want to use

    - name: Install Composer dependencies
      run: composer install

    - name: Create a copy of the .env file
      run: cp .env.example .env

    - name: Generate an application key
      run: php artisan key:generate

    - name: Run database migrations
      run: php artisan migrate --force

    - name: Run PHPUnit tests
      run: php artisan test
